### ISSUE TITLE
Topic: Documentation Improvements

### ISSUE THREAD

**Issue by doinkythederp** [vexide/vexide#95]
## Problem Description

Many vexide crates have functions, fields, structs, or enums that are missing adequate documentation or examples.

## Additional information

Known pain points:

- [x] <https://docs.rs/vexide-devices/0.2.0/vexide_devices/smart/motor/enum.MotorControl.html#variant.Position> is not well documented (#132)
- [x] Some examples for the `time` module are for the wrong functions (#96)
- [x] Many of the details described by the internal display docs (<https://internals.vexide.dev/sdk/display>) could be added to the crate's own doc comments. (#132)
- [x] ADIEncoder is incorrectly documented (#132)

**Comment by GameDungeon** [comment]
ADIEncoder is incorrectly documented https://github.com/vexide/vexide/blob/f02bbccfca44be8ff482b2618285ef6a018024a1/packages/vexide-devices/src/adi/encoder.rs#L9
